src/Models/ContentTypes/CustomTypeProvider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public class CustomTypeProvider : ITypeProvider
    {
        private static readonly Dictionary<Type, string> _codenames = new Dictionary<Type, string>
        {
            {typeof(Event), "event"},
            {typeof(Facility), "facility"},
            {typeof(Venue), "venue"}
        };

        public Type GetType(string contentType)
        {
            return _codenames.Keys.FirstOrDefault(type => GetCodename(type).Equals(contentType));
        }

        public string GetCodename(Type contentType)
        {
            return _codenames.TryGetValue(contentType, out var codename) ? codename : null;
        }
    }
}

src/Models/ContentTypes/Event.Generated.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Event
    {
        public const string Codename = "event";
        public const string DateCodename = "date";
        public const string DescriptionCodename = "description";
        public const string GalleryCodename = "gallery";
        public const string NameCodename = "name";
        public const string SlugCodename = "slug";
        public const string VenueCodename = "venue";

        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public IEnumerable<IAsset> Gallery { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> Venue { get; set; }
    }
}

src/Models/ContentTypes/Event.cs
namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Event
    {
    }
}

src/Models/ContentTypes/Facility.Generated.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Facility
    {
        public const string Codename = "facility";
        public const string LabelCodename = "label";
        public const string StyleCodename = "style";

        public string Label { get; set; }
        public string Style { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}

src/Models/ContentTypes/Facility.cs
namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Facility
    {
    }
}

src/Models/ContentTypes/Venue.Generated.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Venue
    {
        public const string Codename = "venue";
        public const string DescriptionCodename = "description";
        public const string FacilitiesCodename = "facilities";
        public const string GalleryCodename = "gallery";
        public const string NameCodename = "name";
        public const string SlugCodename = "slug";

        public string Description { get; set; }
        public IEnumerable<object> Facilities { get; set; }
        public IEnumerable<IAsset> Gallery { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}

src/Models/ContentTypes/Venue.cs
namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Venue
    {
    }
}

src/Models/ViewModels/EventViewModel.cs
using HeadlessCreator.Models.ContentTypes;

namespace HeadlessCreator.Models.ViewModels{
    public class EventViewModel{
        public Event Event{get;set;} = null;
        public Venue Venue{get;set;} = null;
    }
}

src/Models/ViewModels/HomePageViewModel.cs
using HeadlessCreator.Models.ContentTypes;
using System.Collections.Generic;

namespace HeadlessCreator.Models.ViewModels{
    public class HomePageViewModel{
        public IEnumerable<Event> LatestEvents{get;set;} = new List<Event>();
    }
}

src/Models/ViewModels/VenueViewModel.cs
using HeadlessCreator.Models.ContentTypes;
using System.Collections.Generic;

namespace HeadlessCreator.Models.ViewModels{
    public class VenueViewModel{
        public Venue Venue{get;set;} = null;
        public IEnumerable<Event> UpcomingEvents{get;set;} = new List<Event>();
    }
}

src/Controllers/EventController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HeadlessCreator.Models.ViewModels;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Controllers
{
    public class EventController : Controller
    {
        private readonly ILogger<EventController> _logger;
        protected IDeliveryClient _client { get; }

        public EventController(IDeliveryClient deliveryClient, ILogger<EventController> logger)
        {
            _logger = logger;
            _client = deliveryClient;
        }

        public async Task<IActionResult> Detail(string eventCodename)
        {
            var model = new EventViewModel();

            var ev = await _client.GetItemAsync<HeadlessCreator.Models.ContentTypes.Event>(eventCodename);

            model.Event = ev.Item;

            return View(model);
        }
    }
}

src/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HeadlessCreator.Models.ViewModels;
using Kentico.Kontent.Delivery.Abstractions;
using HeadlessCreator.Models.ContentTypes;
using Kentico.Kontent.Delivery.Urls.QueryParameters;

namespace HeadlessCreator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        protected IDeliveryClient _client { get; }

        public HomeController(IDeliveryClient deliveryClient, ILogger<HomeController> logger)
        {
            _logger = logger;
            _client = deliveryClient;
        }

        public async Task<IActionResult> Index()
        {
            var model = new HomePageViewModel();
            var latestEvents = await _client.GetItemsAsync<Event>(
                new OrderParameter($"elements.{Event.DateCodename}", SortOrder.Ascending),
                new LimitParameter(3)
            );

            model.LatestEvents = latestEvents.Items;

            return View(model);
        }
    }
}

src/Controllers/VenueController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HeadlessCreator.Models.ViewModels;
using Kentico.Kontent.Delivery.Abstractions;
using HeadlessCreator.Models.ContentTypes;
using Kentico.Kontent.Delivery.Urls.QueryParameters;
using Kentico.Kontent.Delivery.Urls.QueryParameters.Filters;

namespace HeadlessCreator.Controllers
{
    public class VenueController : Controller
    {
        private readonly ILogger<VenueController> _logger;
        protected IDeliveryClient _client { get; }

        public VenueController(IDeliveryClient deliveryClient, ILogger<VenueController> logger)
        {
            _logger = logger;
            _client = deliveryClient;
        }

        public async Task<IActionResult> Detail(string venueCodeName)
        {
            var model = new VenueViewModel();

            var venue = await _client.GetItemAsync<Venue>(venueCodeName);

            model.Venue = venue.Item;

            var upcomingEvents = await _client.GetItemsAsync<Event>(
                new AnyFilter($"elements.{Event.VenueCodename}", venue.Item.System.Codename),
                new OrderParameter($"elements.{Event.DateCodename}", SortOrder.Ascending)
            );

            model.UpcomingEvents = upcomingEvents.Items;

            return View(model);
        }
    }
}

src/Views/Event/Detail.cshtml
@model HeadlessCreator.Models.ViewModels.EventViewModel

@{
    var venue = Model.Event.Venue.OfType<Venue>().First();
}

<link href="https://cdn.jsdelivr.net/npm/bulma-carousel/dist/css/bulma-carousel.min.css" rel="stylesheet">

<div class="container">
    <section class="hero is-small is-dark has-background">
        <img src="@Model.Event.Gallery.First().Url" class="hero-background">
        <div class="hero-body">
            <p class="title">
                @Model.Event.Name
            </p>
            <p class="subtitle">
                @Model.Event.Date.Value.ToShortDateString()
            </p>
            <span class="tag is-light"><a asp-controller="Venue" asp-action="Detail"
                    asp-route-venuecodename="@venue.System.Codename">@venue.Name</a></span>
        </div>
    </section>
</div>

<div class="container is-max-desktop">
    <main class="content">
        @Html.Raw(Model.Event.Description)
    </main>
    
    <div class="columns">
        @await Html.PartialAsync("_Venue", venue)
    </div>    
</div>

src/Views/Home/Index.cshtml
@model HeadlessCreator.Models.ViewModels.HomePageViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <section class="hero is-small is-dark">
        <div class="hero-body">
            <p class="title">
                Bushcraft Basics
            </p>
            <p class="subtitle">
                Stay in the woods
            </p>
        </div>
    </section>
</div>

<div class="container">
        <h2 class="title is-2">Upcoming Events</h2>
    
    <div class="columns">
        @foreach (var upcomingEvent in Model.LatestEvents)
        {
            @await Html.PartialAsync("_Event", upcomingEvent)
        }
    </div>
</div>

src/Views/Shared/_Event.cshtml
@model HeadlessCreator.Models.ContentTypes.Event

@{
    var venue = Model.Venue.OfType<Venue>().First();
}

<div class="column is-one-third">
    <div class="card">
        <div class="card-image">
            <figure class="image is-4by3">
                <img src="@Model.Gallery.FirstOrDefault()?.Url" alt="Placeholder image">
            </figure>
            <div class="card-stacked">
                <div class="card-content">
                    <div class="media-content">
                        <p class="title is-4">@Model.Name</p>
                        <span class="tag is-light"><a asp-controller="Venue" asp-action="Detail"
                                asp-route-venuecodename="@venue.System.Codename">@venue.Name</a></span>
                        <p class="subtitle is-6">@(Model.Date.Value.ToLongDateString())</p>
                    </div>

                </div>
                <footer class="card-footer">
                    <div class="card-footer-item has-text-left">
                        <a class="button is-primary" asp-controller="Event" asp-action="Detail"
                            asp-route-eventcodename="@Model.System.Codename">Find out more</a>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</div>

src/Views/Shared/_EventSlim.cshtml
@model HeadlessCreator.Models.ContentTypes.Event

<article class="media">
    <figure class="media-left">
        <p class="image is-128x128">
            <img src="@(Model.Gallery.First().Url)">
        </p>
    </figure>
    <div class="media-content">
        <div class="content">
            <p>
                <strong>@Model.Name</strong>
                <br>
                @Model.Date.Value.ToShortDateString()
            </p>

        </div>
        <nav class="level">
            <div class="level-left">
                <a class="level-item " asp-controller="Event" asp-action="Detail"
                    asp-route-eventcodename="@Model.System.Codename">Find out more</a>
            </div>
        </nav>
    </div>
</article>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Bushcraft Basics</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <link rel="stylesheet" href="/css/site.css">
    <script src="https://kit.fontawesome.com/0003da6654.js" crossorigin="anonymous"></script>
</head>

<body>
    <header class="container">
        <nav class="navbar is-dark is-right" role="navigation">

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                        Home
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="content has-text-centered">
            &copy; 2021 - Powered by <a href="https://kontent.ai" target="_blank" rel="noopener noreferer">Kentico
                Kontent</a>
            <p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/Views/Shared/_Venue.cshtml
@model HeadlessCreator.Models.ContentTypes.Venue

<div class="column is-one-third">
    <div class="card">
        <div class="card-image">
            <figure class="image is-4by3">
                <img src="@Model.Gallery.First().Url" alt="Placeholder image">
            </figure>
            <div class="card-stacked">
                <div class="card-content">
                    <div class="media-content">
                        <p class="title is-4">@Model.Name</p>
                    </div>

                </div>
                <footer class="card-footer">
                    <div class="card-footer-item has-text-left">
                        <a class="button is-primary" asp-controller="Venue" asp-action="Detail"
                            asp-route-venuecodename="@Model.System.Codename">Find out more</a>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</div>

src/Views/Shared/_VenueFacilities.cshtml
@model IEnumerable<HeadlessCreator.Models.ContentTypes.Facility>


<div class="section">
    @foreach (var facility in Model)
    {
        <span class="tag is-info is-large">
            <i class="@facility.Style"></i> @facility.Label</span>
    }
</div>

src/Views/Venue/Detail.cshtml
@model HeadlessCreator.Models.ViewModels.VenueViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <section class="hero is-small is-dark">
        <div class="hero-body">
            <p class="title">
                @Model.Venue.Name
            </p>
            <p class="subtitle">
                Stay in the woods
            </p>
        </div>
    </section>
</div>

<article class="media">
    <figure class="media-left">
        <p class="image" style="max-width:512px">
            <img src="@(Model.Venue.Gallery.First().Url)">
        </p>
    </figure>
    <div class="media-content">
        <div class="content">
            @Html.Raw(Model.Venue.Description)
        </div>
    </div>
</article>

@if(Model.Venue.Facilities.Any())
{
    @await Html.PartialAsync("_VenueFacilities", Model.Venue.Facilities.OfType<Facility>())
}

<div class="container">
    <h2 class="title is-2">Upcoming Events</h2>

    <div class="columns">
        @foreach (var upcomingEvent in Model.UpcomingEvents.Take(3))
        {
            @await Html.PartialAsync("_Event", upcomingEvent)
        }

    </div>

    @if (Model.UpcomingEvents.Count() > 3)
    {
        @foreach (var upcomingEvent in Model.UpcomingEvents.Skip(3))
        {
            @await Html.PartialAsync("_EventSlim", upcomingEvent)
        }
    }
</div>